volumes:
  database_data:

services:
  broker:
    image: rabbitmq:3.11.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  database:
    image: postgres:15.2-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file: ./apps/chat/.env
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat: &chat
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
    env_file: ./apps/chat/.env
    ports:
      - 8000:8080
    volumes:
      - ./apps/chat/app:/app/apps/chat/app
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_healthy

  migrator:
    <<: *chat
    ports: []
    working_dir: /app/apps/chat
    command: alembic upgrade head
    restart: no

  email_connector:
    build:
      context: .
      dockerfile: ./apps/email_connector/Dockerfile
    env_file: ./apps/email_connector/.env
    ports:
      - 8003:8080
    volumes:
      - ./apps/email_connector/app:/app/apps/email_connector/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      retries: 3
      start_period: 15s
    depends_on:
      broker:
        condition: service_healthy

  telegram_connector:
    build:
      context: .
      dockerfile: ./apps/telegram_connector/Dockerfile
    env_file: ./apps/telegram_connector/.env
    ports:
      - 8002:8080
    volumes:
      - ./apps/telegram_connector/app:/app/apps/telegram_connector/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      retries: 3
      start_period: 15s
    depends_on:
      broker:
        condition: service_healthy

  centrifugo:
    image: centrifugo/centrifugo:v6
    volumes:
      - ./configs/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c /centrifugo/config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
